const PDFDocument = require('pdfkit');

const SCHOOL_NAME = process.env.SCHOOL_NAME || 'Hillcrest Academy';
const SCHOOL_ADDRESS = process.env.SCHOOL_ADDRESS || '123 Education Lane, Nairobi, Kenya';
const SCHOOL_PHONE = process.env.SCHOOL_PHONE || '+254 700 000 000';
const SCHOOL_EMAIL = process.env.SCHOOL_EMAIL || 'info@school.com';

const createDocument = (options = {}) => {
  return new PDFDocument({
    size: 'A4',
    margin: 50,
    ...options,
  });
};

const drawHeader = (doc, title, subtitle) => {
  doc.fontSize(10).fillColor('#666666');
  doc.text(SCHOOL_NAME, 50, 50, { align: 'left' });
  doc.fontSize(8).fillColor('#888888');
  doc.text(SCHOOL_ADDRESS, 50, 64, { align: 'left' });
  doc.text(`${SCHOOL_PHONE} | ${SCHOOL_EMAIL}`, 50, 76, { align: 'left' });

  doc.moveTo(50, 95).lineTo(545, 95).stroke('#dddddd');

  doc.fontSize(18).fillColor('#111111');
  doc.text(title, 50, 115, { align: 'center' });
  if (subtitle) {
    doc.fontSize(10).fillColor('#555555');
    doc.text(subtitle, 50, 140, { align: 'center' });
  }
  doc.moveDown(1.5);
};

const drawFooter = (doc) => {
  const pageHeight = doc.page.height;
  doc.fontSize(8).fillColor('#888888');
  doc.text(
    `Generated by School Management System on ${new Date().toLocaleString()}`,
    50,
    pageHeight - 60,
    { align: 'center', width: 495 }
  );
};

const drawTable = (doc, headers, rows, options = {}) => {
  const startX = options.x || 50;
  const startY = doc.y;
  const colWidths = options.colWidths || headers.map(() => 495 / headers.length);
  const rowHeight = options.rowHeight || 22;
  const headerBg = options.headerBg || '#2c5282';
  const align = options.align || 'left';

  let y = startY;

  // Header
  doc.fillColor(headerBg).rect(startX, y, 495, rowHeight).fill();
  doc.fillColor('#ffffff').fontSize(10).font('Helvetica-Bold');
  headers.forEach((header, i) => {
    doc.text(header, startX + colWidths.slice(0, i).reduce((a, b) => a + b, 0) + 5, y + 6, {
      width: colWidths[i] - 10,
      align,
    });
  });
  y += rowHeight;

  // Rows
  doc.font('Helvetica').fillColor('#333333');
  rows.forEach((row, rowIdx) => {
    if (y > doc.page.height - 100) {
      doc.addPage();
      y = 50;
    }
    if (rowIdx % 2 === 1) {
      doc.fillColor('#f7fafc').rect(startX, y, 495, rowHeight).fill();
    }
    doc.fillColor('#333333');
    row.forEach((cell, i) => {
      doc.text(String(cell ?? '-'), startX + colWidths.slice(0, i).reduce((a, b) => a + b, 0) + 5, y + 6, {
        width: colWidths[i] - 10,
        align,
      });
    });
    y += rowHeight;
  });

  doc.y = y + 10;
};

const drawInfoRow = (doc, label, value, options = {}) => {
  const x = options.x || 50;
  const labelWidth = options.labelWidth || 140;
  doc.font('Helvetica-Bold').fontSize(10).fillColor('#555555').text(`${label}:`, x, doc.y, {
    width: labelWidth,
    continued: true,
  });
  doc.font('Helvetica').fillColor('#111111').text(` ${value ?? '-'}`, x + labelWidth, doc.y);
};

module.exports = {
  SCHOOL_NAME,
  SCHOOL_ADDRESS,
  SCHOOL_PHONE,
  SCHOOL_EMAIL,
  createDocument,
  drawHeader,
  drawFooter,
  drawTable,
  drawInfoRow,
};
